// ui/src/app/screen/screen.component.ts
// Profile Monitor SlicLet
//
// Copyright (c) 2024 The Board of Trustees of the Leland Stanford Junior University, through SLAC National Accelerator Laboratory (subject to receipt of any required approvals from the U.S. Dept. of Energy).  All Rights Reserved.
// http://github.com/slaclab/slicops/LICENSE

import { APIService } from '../api.service';
import { Component } from '@angular/core';
import { FormGroup, FormControl } from '@angular/forms';
import { LogService } from '../log.service';

@Component({
    selector: 'app-screen',
    template: `
      <form [formGroup]="form">
        <div class="row" *ngIf="ui_ctx">
          <div *ngIf="errorMessage" class="alert alert-warning">{{ errorMessage }}</div>
          <app-layout [layout]="layout" [formGroup]="form" [parent]="this"
            [ui_ctx]="ui_ctx"></app-layout>
        </div>
      </form>
    `,
    styles: [],
})
export class ScreenComponent {
    errorMessage: string = "";
    image: any = null;
    imageTimeout: any = null;
    layout: any = null;
    form: FormGroup = new FormGroup({});
    ui_ctx: any = null;

    constructor(private apiService: APIService, private log: LogService) {
        this.apiService.call(
            'screen_ui_ctx',
            {},
            (result) => {
                this.ui_ctx = result.ui_ctx;
                this.layout = result.layout;
                let v:any = {};
                for (let f in result.ui_ctx) {
                    v[f] = result.ui_ctx[f].value;
                    this.form.addControl(f, new FormControl(''));
                }
                this.form.patchValue(v);
                this.checkAutoRefresh(result);
            },
            this.handleError.bind(this),
        );
    }

    checkAutoRefresh(result: any) {
        if (! result.ui_ctx) {
            return;
        }
        //TODO(pjm): until server callbacks are supported - run a timeout on each plot
        if (result.ui_ctx.plot.auto_refresh) {
            if (! this.imageTimeout) {
                this.imageTimeout = setTimeout(() => {
                    this.serverAction('plot', true);
                    this.imageTimeout = null;
                }, 1000);
            }
        }
        else if (this.imageTimeout) {
            clearTimeout(this.imageTimeout);
            this.imageTimeout = null;
        }
    }

    handleError(err: any) {
        if (this.errorMessage === undefined) {
            // This would only happen if the handleError callback is setup incorrectly
            this.log.error(['invalid this', this]);
            throw new Error(`Invalid this in handleError: ${this}`);
        }
        this.log.error(['apiService error', err]);
        this.errorMessage = err;
    }

    serverAction(field: string, value: any) {
        this.errorMessage = '';
        this.ui_ctx[field].enabled = false;
        this.apiService.call(
            `screen_${field}`, {
                field_value: value,
            },
            (result) => {
                this.checkAutoRefresh(result);
                if (result.plot) {
                    this.image = result.plot;
                }
                if (result.ui_ctx && field in result.ui_ctx && 'enabled' in result.ui_ctx[field]) {
                }
                else {
                    this.ui_ctx[field].enabled = true;
                }
                //TODO(pjm): need to only update changed fields
                // for now, do no updates on "plot" field changes to avoid all fields refreshing
                // otherwise changing gain or curve_fit_method acts badly when plots are being streaming
                if (result.ui_ctx && field != 'plot') {
                    Object.assign(this.ui_ctx, result.ui_ctx);
                    const values: any = {};
                    for (let f in result.ui_ctx) {
                        if ('value' in result.ui_ctx[f]) {
                            values[f] = result.ui_ctx[f].value;
                        }
                    }
                    this.form.patchValue(values);
                }
            },
            (err) => {
                this.handleError(err);
                this.ui_ctx[field].enabled = true;
            }
        );
    }
}

// ui2/src/views/Screen.vue
<!--
   Profile Monitor SlicLet

   Copyright (c) 2024 The Board of Trustees of the Leland Stanford Junior University, through SLAC National Accelerator Laboratory (subject to receipt of any required approvals from the U.S. Dept. of Energy).  All Rights Reserved.
 http://github.com/slaclab/slicops/LICENSE
-->
<template>
    <form>
        <div
            v-if="ui_ctx"
            class="row">
            <div
                v-if="errorMessage"
                class="alert alert-warning">{{ errorMessage }}
            </div>
            <VLayout
                :layout="layout.value"
                :ui_ctx="ui_ctx.value"
            />
        </div>
    </form>
</template>

<script setup>
 import { ref, reactive } from 'vue';
 import { apiService } from '@/service/api';
 import VLayout from '@/components/VLayout.vue';

 const errorMessage = ref('');
 const layout = reactive({});
 const ui_ctx = reactive({});

 const handleError = (error) => {
     errorMessage.value = error;
 };

 const serverAction = (field, value) => {
     errorMessage.value = '';
     ui_ctx.value[field].enabled = false;
     apiService.call(
         `screen_${field}`, {
             field_value: value,
         },
         (result) => {
             updateUIState(result);
             //TODO(pjm): only enable if enabled not set in result
             ui_ctx.value[field].enabled = true;
         },
         (err) => {
             handleError(err);
             ui_ctx.value[field].enabled = true;
         }
     );
 };

 const updateUIState = (result) => {
     console.log('update:', result);
     if (result.plot) {
         ui_ctx.value.image = result.plot;
     }
     if (result.ui_ctx) {
         Object.assign(ui_ctx.value, result.ui_ctx);
     }
 }

 (() => {
     apiService.call(
         'screen_ui_ctx',
         {},
         (result) => {
             ui_ctx.value = result.ui_ctx;
             layout.value = result.layout;
             ui_ctx.value.serverAction = serverAction;
         },
         (error) => {
             camera.value = 'Error getting camera';
         },
     );

     apiService.subscribe('screen_update', {}, updateUIState, handleError);
 })();
</script>
