// ui3/src/App.vue
<template>
  <div class="container-fluid">
    <router-view></router-view>
  </div>
</template>

<script>
export default {
  name: 'App',
  mounted() {
    // Respond to system color preference changes (light vs dark)
    const prefersDarkScheme = window.matchMedia('(prefers-color-scheme: dark)');
    prefersDarkScheme.addEventListener('change', this.handleColorScheme);
    this.handleColorScheme(prefersDarkScheme);
  },
  methods: {
    handleColorScheme(event) {
      document.querySelector('html').setAttribute(
        'data-bs-theme',
        event.matches ? 'dark' : 'light'
      );
    }
  },
  beforeUnmount() {
    // Clean up event listener
    window.matchMedia('(prefers-color-scheme: dark)').removeEventListener('change', this.handleColorScheme);
  }
}
</script>

// ui/src/app/app.component.ts
import { Component, Renderer2 } from '@angular/core';

@Component({
    selector: 'app-root',
    template: `
      <div class="container-fluid">
        <router-outlet></router-outlet>
      </div>
    `,
    styles: [],
})
export class AppComponent {
    constructor(private renderer: Renderer2) {
        // respond to system color preference changes (light vs dark)
        const p = window.matchMedia('(prefers-color-scheme: dark)');
        p.addEventListener('change', this.handleColorScheme.bind(this));
        this.handleColorScheme(p);
    }

    handleColorScheme(event: MediaQueryList | MediaQueryListEvent) {
        this.renderer.setAttribute(
            document.querySelector('html'),
            'data-bs-theme',
            event.matches ? 'dark' : 'light',
        );
    }
}
